#!bin/bash

userid=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
folder-path="/var/log/shell-scripting"
mkdir -p $folder-path
script=$( echo $0 )
file="$folder-path/$script-name.log"
echo "this script has started running at : $(date)"


if [ $userid -ne 0 ]; then 
    echo "ERROR:please run this script with root provileges"
    exit 1
fi
validate(){
if [ $1 -ne 0 ]; then
    echo "ERROR: installation of $2 is failed"
    exit 1
else 
    echo " installation of $2 is success"
fi

}
dnf list installed nginx &>>$file
if [ $? -ne 0 ]; then
    dnf install nginx -y &>>$file 
    validate $? "nginx" 
else
    echo -e "nginx is already exist.....$Y skipping $N"
fi
dnf list installed mysql &>>$file
if [ $? -ne 0 ]; then
    dnf install mysql -y &>>$file
    validate $? "mysql"

else
    echo -e "mysql is already exist.....$Y skipping $N"
fi
dnf list installed python &>>$file
if [ $? -ne 0 ]; then
    dnf install python3 -y
    validate $? "python3" &>>$file
else
    echo -e "python is already exist.....$Y skipping $N"
fi

