#!/bin/bash
userid=$( id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"
folder="/var/log/shell-script"
script=$( echo $0)
log_file="$folder/$script.log"
mkdir -p $folder
echo "this scrip has started at : $(date)"
if [ $userid -ne 0 ]; then
    echo "ERROR please run the script with sudo privillages"
    exit 1
fi
# validate(){
#     if [ $1 -ne 0 ]; then
#         echo -e "installation of $2...... $R failed $N" | tee -a $log_file
#         exit 1
#     else
#         echo -e "installation of $2......$G success $N" | tee -a $log_file
#     fi
#}
VALIDATE(){ # functions receive inputs through args just like shell script args
    if [ $1 -ne 0 ]; then
        echo -e "Installing $2 ... $R FAILURE $N" | tee -a $log_file
        exit 1
    else
        echo -e "Installing $2 ... $G SUCCESS $N" | tee -a $log_file
    fi
}
for package in $@
do
    dnf list installed $package 
    if [ $? -ne 0 ]; then
        dnf install $package -y &>>$log_file
        validate $? "$package"
    else
        echo "$package is already installed.... $y skipping $N"
    fi
done



