#!/bin/bash
echo "course name is : $course" #environment variable

#--> .bashrc using vim editor
# enter variable ( export course="shell scripting")
#source .bashrc
# now the varibale is set we can user it anywhere
