#!/bin/bash
userid=$(id -u)
if [ $userid -ne 0 ]; then
	echo "ERROR: please run this script with root user"
	exit 1
fi
dnf install nginx -y
if [ $? -ne 0 ]; then #here $? is exit status of last command
	echo "ERROR: installation of nginx is failed"
	exit 1
else 
	echo "installing nginx is success"
fi
