#!/bin/bash
userid=$((id -u))
if [ $userid -ne 0 ]; then
	echo "please run the script with root user"
	exit 1
fi
dnt install nginx -y
if [ $? -ne 0]; then 
	echo "ERROR: installation of nginx is failed"
	exit 1
else 
	echo "installing nginx is success"
fi
