#!/bin/bash
userid=$( id -u )
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

if [ $userid -ne 0 ]; then
    echo " ERROR please rub the script with sudo privillages"
    exit 1
fi 
validate(){
    if [ $1 -ne 0 ]; then
        echo -e " installation of $2 is  $R failed $N"
        exit 1
    else 
        echo -e " installation of $2 is $G success $N"
    fi
}

dnf list installed nginx
if [ $? -ne 0 ]; then
    dnf install nginx -y
    validate $? "nginx"
else 
    echo -e "Nginx is already exist.......$Y skipping $N"
fi

dnf list installed mysql
if [ $? -ne 0 ]; then
    dnf install mysql -y
    validate $? "MYSQL"
else 
    echo -e "MYSQL is already exist.......$Y skipping $N"
fi

dnf list installed python3
if [ $? -ne 0 ]; then
    dnf install python3 -y
    validate $? "Python3"
else 
    echo -e "Python3 is already exist.......$Y skipping $N"
fi 
