#!/bin/bash
userid=$( id -u )
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"
log_floder="/var/logs/mylogs"
echo "Script started executed at: $(date)" | tee -a $file
log_file="$log_folder/$script.log"
mkdir -p $log_folder

if [ $userid -ne 0 ]; then
    echo "ERROR please rub the script with sudo privillages"
    exit 1
fi 
validate(){
    if [ $1 -ne 0 ]; then
        echo -e " installation of $2 is  $R failed $N" | tee -a $file
        exit 1
    else 
        echo -e " installation of $2 is $G success $N" | tee -a $file
    fi
}

dnf list installed nginx &>>$log_file
if [ $? -ne 0 ]; then
    dnf install nginx -y &>>$log_file 
    validate $? "nginx"
else 
    echo -e "Nginx is already exist.......$Y skipping $N" | tee -a $file
fi

dnf list installed mysql &>>$log_file
if [ $? -ne 0 ]; then
    dnf install mysql -y &>>$log_file
    validate $? "MYSQL"
else 
    echo -e "MYSQL is already exist.......$Y skipping $N" | tee -a $file
fi

dnf list installed python3 &>>$log_file
if [ $? -ne 0 ]; then
    dnf install python3 -y &>>$log_file
    validate $? "Python3"
else 
    echo -e "Python3 is already exist.......$Y skipping $N" | tee -a $file
fi 
